### ISSUE TITLE
Nuget availability

### ISSUE THREAD

**Issue by LadislavBohm** [alphamax/TinyWorkflow#2]
I'm successfully using this great library in our project via referencing a .DLL. But it would be much better to have it referenced from Nuget.

Could you please publish it to Nuget?

**Comment by alphamax** [comment]
I will try 👍 I will have a look of nuget publishing this week !

**Comment by alphamax** [comment]
Job done (seems to work): https://preview.nuget.org/packages/Tiny-Workflow/.
If there is any problem, re-open this ticket :)
